### ISSUE TITLE
Issues with SVG attributes

### ISSUE THREAD

**Issue by hitpopdimestop** [fgnass/domino#112]
Hello!
I have a problem with using SVG placed directly into HTML in my Angular 5 project. angular/platform-server uses domino version 1.0.30 as a dependency and based on the error I get it seems like it's a domino's issue and not angular's.

My error looks like this (shortened):
    
`    ERROR { NAMESPACE_ERR: NAMESPACE_ERR (14): the operation is not allowed by Namespaces in XML`
    
    at Object.exports.NamespaceError (/Users/hitpopdimestop/Work/web2.0/server.js:23454:45)
    at SVGSVGElement.setAttribute (/Users/hitpopdimestop/Work/web2.0/server.js:48352:50)
    at DominoAdapter.BrowserDomAdapter.setAttribute (/Users/hitpopdimestop/Work/web2.0/server.js:28499:47)
    at EmulatedEncapsulationServerRenderer2.DefaultServerRenderer2.setAttribute (/Users/hitpopdimestop/Work/web2.0/server.js:133321:90)
    at BaseAnimationRenderer.setAttribute (/Users/hitpopdimestop/Work/web2.0/server.js:140045:23)
    at DebugRenderer2.setAttribute (/Users/hitpopdimestop/Work/web2.0/server.js:21648:23)
    at createElement (/Users/hitpopdimestop/Work/web2.0/server.js:16886:22)
    at createViewNodes (/Users/hitpopdimestop/Work/web2.0/server.js:20045:61)
    at callViewAction (/Users/hitpopdimestop/Work/web2.0/server.js:20518:13)
    at execComponentViewsAction (/Users/hitpopdimestop/Work/web2.0/server.js:20427:13)

```
  code: 14,
  message: 'NAMESPACE_ERR (14): the operation is not allowed by Namespaces in XML',
  name: 'NAMESPACE_ERR', ...
```

The same error is also described in details here:
https://github.com/angular/material2/issues/8241

**Comment by cscott** [comment]
Ah, this appears to be a part of the DOM spec that no one ever implemented (except domino!):
https://bugzilla.mozilla.org/show_bug.cgi?id=315805
https://www.w3.org/Bugs/Public/show_bug.cgi?id=16493

The check was removed from the DOM spec in https://github.com/whatwg/dom/commit/9e036e4b309eb8fc9dc75283b24f50fe9498a928

I'll fix domino to follow the latest DOM spec (ie, remove the check).
