### ISSUE TITLE
Error: This method is not implemented in DominoAdapter: getCookie

### ISSUE THREAD

**Issue by sathishvikkas** [fgnass/domino#143]
Error: This method is not implemented in DominoAdapter: getCookie
at _notImplemented (E:\myapp\src\main\kiosk\dist\server\main.js:251176:16)
at DominoAdapter.getCookie (E:\myapp\src\main\kiosk\dist\server\main.js:251367:69)

**Comment by CaerusKaru** [comment]
Duplicate of https://github.com/fgnass/domino/issues/132

**Comment by cscott** [comment]
Closing as duplicate.
