### ISSUE TITLE
Question: How to monkey patch Canvas

### ISSUE THREAD

**Issue by hmf** [fgnass/domino#149]
Apologies for this question but am very inexperienced regarding HTML + JS. Any pointers are appreciated.

I looked at issues #113 but could not figure out how to bypass this.  I would like to *monkey-patch* Domino's Canvas for plotting purposes.  I am executing a JS script in the GraaJS engine that creates a window globally so that it can be used by plotly (see below). 

The `mockCanvas` does not seem to be doing its thing. Can anyone tell me were I am erring? 

TIA. 

```js
//
// Mock Canvas / Context2D calls
//
function mockCanvas (win) {
    win.HTMLCanvasElement.prototype.getContext = function () {
        return {
            fillRect: function() {},
            clearRect: function(){},
            getImageData: function(x, y, w, h) {
                return  {
                    data: new Array(w*h*4)
                };
            },
            putImageData: function() {},
            createImageData: function(){ return []},
            setTransform: function(){},
            drawImage: function(){},
            save: function(){},
            fillText: function(){},
            restore: function(){},
            beginPath: function(){},
            moveTo: function(){},
            lineTo: function(){},
            closePath: function(){},
            stroke: function(){},
            translate: function(){},
            scale: function(){},
            rotate: function(){},
            arc: function(){},
            fill: function(){},
            measureText: function(){
                return { width: 0 };
            },
            transform: function(){},
            rect: function(){},
            clip: function(){},
        };
    }

    win.HTMLCanvasElement.prototype.toDataURL = function () {
        return "";
    }
}

// Make sure we have a CSSStyleSheet for PlotLy
// See https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule
load("./mdocs/src/mdocs/cssom.js")

// Make sure we have a working DOM for jsdom
load("./mdocs/src/mdocs/domino.js")
//console.log(domino);
//console.log(domino.createWindow);

// Create a global window for jsdom
var window = domino.createWindow('<h1>Hello world</h1>', 'http://example.com');
mockCanvas(window);
var document = window.document;

// Add the style sheet to the window
var s = new cssom.CSSStyleSheet;
s.insertRule("a {color: blue}", 0);
// Only prints something if a style has been added
//console.log('styleSheet s = ' + s);

// PlotLy requires a style sheet with a specific ID
var uid = 'global'
var id = 'plotly.js-style-' + uid;
var style = document.getElementById(id);
if(!style) {
  //console.log('No CSS found!');
  style = document.createElement('style');
  //console.log(style);
  style.setAttribute('id', id);
  // WebKit hack :(
  style.appendChild(document.createTextNode(''));
  document.head.appendChild(style);
  style.sheet = s;
}
var styleSheet = style.sheet;
style.sheet.insertRule('.foo{color:red;}', 0);
//console.log('styleSheet style.sheet = ' + styleSheet);

// Add a shim for the DOMParser. PlotLy needs this. jsdom can provide this.
//window.DOMParser = function() {};
var DOMParser = function() {};

/* This will fail with:
Exception in thread "main" Error: NotYetImplemented
	at <js> exports.nyi(mdocs/src/mdocs/domino.js:23327:759865-759894)
	at <js> 551(mdocs/src/mdocs/plotly-latest.js:76405:2989460-2989489)

 PlotLy expects a browser with a Canvas:

 if(typeof document !== 'undefined') {
  defaultCanvas = document.createElement('canvas')
  defaultCanvas.width = 8192
  defaultCanvas.height = 1024
  defaultContext = defaultCanvas.getContext("2d")
}

Uses"vectorize-text":551
see https://github.com/mikolalysenko/vectorize-text
*/

try {

  //load("https://cdn.plot.ly/plotly-latest.min.js");
  //load("https://cdn.plot.ly/plotly-latest.js");
  load("./mdocs/src/mdocs/plotly-latest.js");
  throw "Should fail with 'Error: NotYetImplemented'";
}
catch {
  // Should fail
}

```

**Comment by cscott** [comment]
You probably have to set `__domino_frozen__ = false`; see #138.
