### ISSUE TITLE
css parser fails during style.setProperty() if variable name starts with "--"

### ISSUE THREAD

**Issue by bob-walters** [fgnass/domino#175]
Noticed in domino 2.1.6 via angular9 universal.

If `someElement.style.setProperty(key, value)` is called using a key which begins with "--", the following parsing error is reported:

```
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at TokenStream.LA (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/cssparser.js:810:1)
    at TokenStream.advance (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/cssparser.js:683:1)
    at Parser._readDeclarations (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/cssparser.js:3402:1)
    at Parser.parseStyleAttribute (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/cssparser.js:3581:1)
    at parseStyles (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/CSSStyleDeclaration.js:23:1)
    at CSSStyleDeclaration.value (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/node_modules/domino/lib/CSSStyleDeclaration.js:142:1)
    at AppComponent.<anonymous> (/Users/bobw/workspaces/te2/marketplace/frontend/dist/frontend/server/webpack:/src/app/app.component.ts:97:27)
    at Generator.next (<anonymous>)
....
```

Note:
* key variables which simply contain a "--" work, so long as they dont start with that value
* variables which start with a single "-" also work.

I.e. this is likely an edge case that the parser is not correctly handling.

**Comment by Burgov** [comment]
there is already an issue for this: https://github.com/fgnass/domino/issues/165

**Comment by cscott** [comment]
Should be fixed now via 3763c8c20719aefb7f3c972baf7a2d3777a78085.
