### ISSUE TITLE
TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by mdholloway** [fgnass/domino#71]
I deployed yesterday's changes in the mobile content service this morning, but reverted shortly thereafter because of a flood of these:

`TypeError: Cannot convert object to primitive value    
 at Object.create._serialize.value (/srv/deployment/mobileapps/deploy/node_modules/domino/lib/CSSStyleDeclaration.js:55:23)
 at Object.create.setProperty.value (/srv/deployment/mobileapps/deploy/node_modules/domino/lib/CSSStyleDeclaration.js:134:10)    
 at Object.defineProperty.set (/srv/deployment/mobileapps/deploy/node_modules/domino/lib/CSSStyleDeclaration.js:265:12)
 at Object.hideIPA (/srv/deployment/mobileapps/deploy/src/lib/transformations/hideIPA.js:45:34)
 at runAllSectionsTransforms (/srv/deployment/mobileapps/deploy/src/lib/transforms.js:242:13)
 at Object.runParsoidDomTransforms (/srv/deployment/mobileapps/deploy/src/lib/transforms.js:263:5)
 at Request.<anonymous> (/srv/deployment/mobileapps/deploy/src/lib/parsoid-access.js:181:24)
 at Request.tryCatcher (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/util.js:11:23)
 at Promise._settlePromiseFromHandler (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:491:31)    
 at Promise._settlePromise (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:548:18)
 at Promise._settlePromise0 (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:593:10)
 at Promise._settlePromises (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:676:18)
 at Promise._fulfill (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:617:18)
 at Promise._resolveCallback (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:418:57)
 at Promise._settlePromiseFromHandler (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:504:17)  
 at Promise._settlePromise (/srv/deployment/mobileapps/deploy/node_modules/bluebird/js/release/promise.js:548:18)`

**Comment by cscott** [comment]
It looks like someone is overriding Object.create in your stack.  What is `Object.hideIPA`?

We use `Object.create(null)` in multiple places in domino, I'm surprised you haven't run across this before.
