### ISSUE TITLE
TypeError: combinators[op] is not a function

### ISSUE THREAD

**Issue by arlolra** [fgnass/domino#79]
Filing this as a reminder,

```
> document.querySelector("#cite_note-13.3F_It_Can't_Be!-3");
TypeError: combinators[op] is not a function
    at compile (./domino/lib/select.js:653:32)
    at find (./domino/lib/select.js:804:14)
    at module.exports.exports (./domino/lib/select.js:850:10)
    at Object.create.querySelector.value (./domino/lib/Document.js:650:12)
    at repl:1:10
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

Chrome throws an `Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#cite_note-13.3F_It_Can't_Be!-3' is not a valid selector.`

**Comment by arlolra** [comment]
Considering upstream isn't accepting your pulls, maybe it's time to switch to another css selector engine? sizzle or css-select seem like ok options.

**Comment by cscott** [comment]
I started writing a patch for this already, which also fixes zest to
understand the CSS backslash escape mechanism.  But it might be worth
checking out other selector libraries.

**Comment by arlolra** [comment]
Thanks :)
