### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined (cssparser.js:810:29)

### ISSUE THREAD

**Issue by mdholloway** [fgnass/domino#86]
We're running into a (relatively infrequent) error in the mobileapps service that traces back to domino.  

Example request: 
https://de.wikipedia.org/api/rest_v1/page/mobile-sections/Verallgemeinerter_Laplace-Operator

Stack trace (from local machine):
```
TypeError: Cannot read property 'type' of undefined
  at TokenStreamBase.LA (/Users/mholloway/mobileapps/node_modules/domino/lib/cssparser.js:810:29)
  at TokenStreamBase.advance (/Users/mholloway/mobileapps/node_modules/domino/lib/cssparser.js:683:20)
  at Parser.additions._readDeclarations (/Users/mholloway/mobileapps/node_modules/domino/lib/cssparser.js:3402:42)
  at Parser.additions.parseStyleAttribute (/Users/mholloway/mobileapps/node_modules/domino/lib/cssparser.js:3581:22)
  at parseStyles (/Users/mholloway/mobileapps/node_modules/domino/lib/CSSStyleDeclaration.js:23:10)
  at Object.create._parsed.get (/Users/mholloway/mobileapps/node_modules/domino/lib/CSSStyleDeclaration.js:38:28)
  at Object.create.setProperty.value (/Users/mholloway/mobileapps/node_modules/domino/lib/CSSStyleDeclaration.js:126:22)
  at Object.defineProperty.set (/Users/mholloway/mobileapps/node_modules/domino/lib/CSSStyleDeclaration.js:304:12)
  at Object.setMathFormulaImageMaxWidth (/Users/mholloway/mobileapps/lib/transformations/setMathFormulaImageMaxWidth.js:17:40)
  at Object.transforms.addRequiredMarkup (/Users/mholloway/mobileapps/lib/transforms.js:233:33)
  at Request.<anonymous> (/Users/mholloway/mobileapps/lib/parsoid-access.js:153:24)
  at Request.tryCatcher (/Users/mholloway/mobileapps/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/Users/mholloway/mobileapps/node_modules/bluebird/js/release/promise.js:504:31)
  at Promise._settlePromise (/Users/mholloway/mobileapps/node_modules/bluebird/js/release/promise.js:561:18)
  at Promise._settlePromise0 (/Users/mholloway/mobileapps/node_modules/bluebird/js/release/promise.js:606:10)
  at Promise._settlePromises (/Users/mholloway/mobileapps/node_modules/bluebird/js/release/promise.js:685:18)
```

The line in the mobileapps service triggering this error is here: 
https://github.com/wikimedia/mediawiki-services-mobileapps/blob/master/lib/transformations/setMathFormulaImageMaxWidth.js#L17

**Comment by d00rman** [comment]
@cscott ping? Mind looking into this issue?

**Comment by arlolra** [comment]
He's away this week.

**Comment by cscott** [comment]
Did you ever get to the bottom of this?  I vaguely recall looking into it, and it was some bogus CSS code that was triggering this?  Is it related to #79?

**Comment by mdholloway** [comment]
Ah, thanks for the ping, I'd completely forgotten about this.  The transform that was triggering this is no longer part of the service, so I guess this particular issue is moot.  #79 certainly looks familiar but I'm not sure it's related here.

I'm not sure about the specific causality but generally it seemed like we were triggering very occasional errors in domino when our (legacy) transforms would directly manipulate page styles.  We're getting away from that in favor of just marking up elements with class names that our CSS knows how to handle (e.g., https://gerrit.wikimedia.org/r/#/c/309170/), so hopefully that category of error is a thing of the past.
