### ISSUE TITLE
TypeError: combinators[op] is not a function

### ISSUE THREAD

**Issue by berndsi** [fgnass/domino#95]
The symptoms are the same as #79, but this is using 1.0.27. So theoretically that should be already fixed.

```
const domino = require('domino');
const document = domino.createDocument(`<body><a href="foo's">bar</a></body>`);
document.querySelectorAll("a[href=foo's]");
TypeError: combinators[op] is not a function
    at compile (./node_modules/domino/lib/select.js:674:32)
    at find (./node_modules/domino/lib/select.js:826:14)
    at module.exports.exports (./node_modules/domino/lib/select.js:872:10)
    at Object.create.querySelectorAll.value (./node_modules/domino/lib/Document.js:682:17)
    at repl:1:5
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:82:20)
```

If I double the single-quotes then I don't get this error but then it also doesn't find what I'm looking for.

```
npm list domino
...
└── domino@1.0.27
```

**Comment by arlolra** [comment]
Hmm, yeah, that should throw a `SyntaxError`.  What you want is the escaped `document.querySelectorAll("a[href=foo\\'s]");`

**Comment by berndsi** [comment]
It doesn't seem to find my node, though:
```
JSON.stringify(document.querySelectorAll("a[href=foo\\'s]"), null, 2);
'[]'
```

**Comment by arlolra** [comment]
I see,

```
diff --git a/lib/select.js b/lib/select.js
index 8568fd4..8be9d0f 100644
--- a/lib/select.js
+++ b/lib/select.js
@@ -732,7 +732,7 @@ var tok = function(cap, qname) {
       cap[6] = cap[6].replace(/ +i$/, '');
       i = i > cap[6].length;
     }
-    return selectors.attr(decodeid(cap[4]), cap[5] || '-', unquote(cap[6]), i);
+    return selectors.attr(decodeid(cap[4]), cap[5] || '-', unquote(decodeid(cap[6])), i);
   }
 
   throw new Error('Unknown Selector.');
```
